
# gcloud builds submit --config=cloudbuild.yaml .
steps:
- id: '1 Run Initial Setup'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |-       
       bash initial_setup.sh ${_DAGS_FOLDER}
options:
  logging: CLOUD_LOGGING_ONLY